config:
    log:
      dir: null
      filename: null
    aws:
        region: null
        AccessKeyId: null
        SecretAccessKey: null
        SnsTopicArn: null
        SnsSubjectPrefix: "[AmiRoteto]"
    profile: "default"
    tags: null
